/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { RewardControl } from "./RewardControl";
export type { RoleControl } from "./RoleControl";
export type { SnackclubTournamentsPayout } from "./SnackclubTournamentsPayout";
